### ISSUE TITLE
What exactly is this repository? What benefits does it have over the original uyuni-project?

### ISSUE THREAD

**Issue by KiyoIchikawa** [sbluhm/uyuni#61]
# Question
_What do you want to know about Uyuni?_

What exactly is this repository? What benefits does it have over the original uyuni-project?

We are currently running a PoC of the OpenSUSE Leap Uyuni to test managing OEL7 and OL8 systems. We have been running into some oddities and difficulties with package management (specifically with streams/modules) and wonder if running Uyuni on something RHEL8 based would better support our systems/make it easier to manage.

**Comment by sbluhm** [comment]
@KiyoIchikawa , I am not sure why I don't get notifications so apologies for the late reply.

This is my development repo. All the changes in here are being fed to Uyuni master.
Uyuni Master does run on AlmaLinux 8 and should run on Rockly, CentOD and RHEL8 (if not, let me know).

I am working on fixing any known issues and then pushing them to master.
My Spacewalk instance has been moved over to Uyuni 2021.12 on Almalinux8 and is being used productive. For me, there are no showstoppers or functionality deficits compared to Spacewalk.

Uyuni on RHEL should not differ to Uyuni on Leap. Due to bugs on either Leap or on RHEL does make it work better in some parts left and some parts right. But in the end they should all be merged in the middle. If you are running SUSE servers anyways, stick to official Uyuni releases. If you prefer RHEL, you can install Uyuni master on a test environment to see if this works for you.

Monitoring does not work yet as I have to still figure out `go`. Quite some cosmetics are open but you won't notice them during operations (file paths are mixed between SUSE/RHEL structure for non-critical files).

Modules is an interesting topic and they are certainly annoying in Uyuni. The way Uyuni solves it for you to create a custom channel called "Content Lifecycle` where it autogenerates a channel based on selected modules. You then assign the channel to the systems. I don't like this approach and I am planning to (later) implement an approach to fetch possible updates from the systems directly instead of calculating them on the server. #59 

You can try the installation by following these instructions: https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-centos-8.html (short version, just run `curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/install.sh | bash` and it does it all for you).

Let me know if you have any other questions.

**Comment by KiyoIchikawa** [comment]
Are there any plans to have Uyuni available via RPM?

**Comment by sbluhm** [comment]
Yes, it is already. As you can see from the linked instructions, it is just a simple `dnf install patterns_uyuni-server` (once the repo is added).
https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-centos-8.html

The script mentioned above just adds the prerequisites plus the prerequisites for the master branch version as there is no release version available just yet. You can also follow the instructions step by step instead.

I guess the idea is to add the Uyuni repo and then just do the dnf install patterns-uyuni_server. All other required files from other repos and modules would be replicated to the uyuni repo.
