### ISSUE TITLE
Installation using Oracle Linux 8

### ISSUE THREAD

**Issue by corosou** [sbluhm/uyuni#77]
Hi,

I'm trying to install using Oracle Linux 8, but I'm running into several version issues:

1) reprepro - required version > 5.4 and none provided by any of the repos the instructions call for. I had to recompile from source RPM (no biggie)

> nothing provides reprepro >= 5.4 needed by susemanager-4.4.0-220400.11.1.uyuni2.x86_64

2) cobbler - instructions call for `yum module enable cobbler:3` when I think that should be `yum module enable cobbler:3.3`, but even that doesn't work, as it wants version 3.3.3 min and the EPEL-Modular repo only provides 3.3.2 (this I prefer not to recompile on my own)

> nothing provides cobbler >= 3.3.3 needed by spacewalk-backend-tools-4.4.0-220400.9.4.uyuni2.noarch

> yum info cobbler
> Available Packages
> Name         : cobbler
> Version      : 3.3.2

So, my question is, are your instructions supposed to work at this time?

It seems like Uyuni wants higher versions than what is currently available from the repos you call for.

Thanks for your time!

**Comment by sbluhm** [comment]
Hello @corosou ,

thank you for trying out the installation. Unfortunately, the EL8 version stopped working since the Uyuni switch to SUSE Leap 15.4.

Due to the required effort, I decided to focus on the EL9 implementation. The package installation was in a working state but I doubt it currently is as there have some more package changes. Unfortunately I have to focus on other topics at the moment so Uyuni is on hold for me for time being.

Once I find time, I will get it working again and let you know. (Aim is to have it running again on EL9 by end of year).

Best wishes,

Stefan

**Comment by corosou** [comment]
Hi Stefan,

Just wanted to mention that I sent you an email to the address you have listed on your website. Just in case your spam filter catches it or you don't monitor that email regularly. Hope you get a chance to read it!

Regards,

-Leon

**Comment by sbluhm** [comment]
@corosou , FYI, I did take some time this week to see if I can get the packages to build again. Result: I got hooked and Uyuni is building and packages installing again on Enterprise Linux 9.
Next would be to get the setup routine to run again for PGSQL and you should have a nice beta setup for EL9.
(https://www.bluhm-de.com/content/os-tools/en/applications/uyuni/installing-uyuni-on-almalinux-9.html)
